### ISSUE TITLE
Where to add proxies?

### ISSUE THREAD

**Issue by NiNj4HAX** [ZelliDev/Discord_NitroGenerator_Basic#6]
Where do i add proxies ? it get's - "Trop de Requêtes / 429" Message?
So where can i add proxies?

**Comment by ZelliDev** [comment]
You simply have to add a WebProxy on your WebClient.Proxy


`WebClient web = new WebClient();
WebProxy proxy = new WebProxy(" proxy server url here");
web.Proxy = proxy;
string str = client.DownloadString("http://www.google.com");`
